<a href="https://colab.research.google.com/github/r2x4/hackathon/blob/main/hackathon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  

----
# <center><font color="#615FFF" size="8"> Hackathon Oracle </font></center>
----

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
data = pd.read_excel("/content/data.xlsx")

In [14]:
data.shape

(7043, 21)

In [15]:
data.sample(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
2079,5804-HYIEZ,Male,0,Yes,Yes,70,Yes,Yes,Fiber optic,Yes,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,106.05,7554.05,No
5886,1709-EJDOX,Female,0,Yes,Yes,47,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.75,948.90,No
1372,9793-WECQC,Male,0,No,No,23,Yes,No,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,No,Mailed check,95.30,2192.90,No
4292,2091-RFFBA,Female,1,No,No,31,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,73.90,2217.15,Yes
4220,4644-OBGFZ,Male,0,Yes,Yes,55,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Mailed check,19.50,1026.35,No

In [16]:
data.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [17]:
data.rename(columns={
    'customerID': 'id_cliente',
    'gender': 'genero',
    'SeniorCitizen': 'adulto_mayor',
    'Partner': 'tiene_pareja',
    'Dependents': 'tiene_dependientes',
    'tenure': 'antiguedad_meses',
    'PhoneService': 'servicio_telefono',
    'MultipleLines': 'lineas_multiples',
    'InternetService': 'servicio_internet',
    'OnlineSecurity': 'seguridad_en_linea',
    'OnlineBackup': 'respaldo_en_linea',
    'DeviceProtection': 'proteccion_dispositivo',
    'TechSupport': 'soporte_tecnico',
    'StreamingTV': 'streaming_tv',
    'StreamingMovies': 'streaming_peliculas',
    'Contract': 'tipo_contrato',
    'PaperlessBilling': 'facturacion_electronica',
    'PaymentMethod': 'metodo_pago',
    'MonthlyCharges': 'cargo_mensual',
    'TotalCharges': 'cargos_totales',
    'Churn': 'abandono_cliente'
}, inplace=True)

In [18]:
data.sample(5)

,id_cliente,genero,adulto_mayor,tiene_pareja,tiene_dependientes,antiguedad_meses,servicio_telefono,lineas_multiples,servicio_internet,seguridad_en_linea,...,proteccion_dispositivo,soporte_tecnico,streaming_tv,streaming_peliculas,tipo_contrato,facturacion_electronica,metodo_pago,cargo_mensual,cargos_totales,abandono_cliente
2339,4094-NSEDU,Female,1,No,No,21,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,94.25,1973.75,Yes
3435,4450-DLLMH,Male,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Credit card (automatic),71.30,157.75,No
5469,6538-POCHL,Male,0,No,No,33,Yes,No,Fiber optic,No,...,Yes,No,No,No,Month-to-month,Yes,Credit card (automatic),79.00,2576.80,No
1746,3963-RYFNS,Female,0,No,No,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),116.45,8013.55,No
6226,2097-YVPKN,Male,0,No,No,65,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,1654.75,No

In [19]:
data.memory_usage(deep=True).sum() / 1024**2

np.float64(6.506089210510254)

In [20]:
data.isnull().sum()

id_cliente                  0
genero                      0
adulto_mayor                0
tiene_pareja                0
tiene_dependientes          0
antiguedad_meses            0
servicio_telefono           0
lineas_multiples            0
servicio_internet           0
seguridad_en_linea          0
respaldo_en_linea           0
proteccion_dispositivo      0
soporte_tecnico             0
streaming_tv                0
streaming_peliculas         0
tipo_contrato               0
facturacion_electronica     0
metodo_pago                 0
cargo_mensual               0
cargos_totales             11
abandono_cliente            0
dtype: int64